use perl5 instead of sed, grep

diff --git a/gfwlist2privoxy b/gfwlist2privoxy
--- a/gfwlist2privoxy
+++ b/gfwlist2privoxy
@@ -1,60 +1,47 @@
 #!/bin/sh
 
-## gfwlist.action 文件
+# Desc: convert gfwlist.txt into privoxy.action
+# Usage: sh gfwlist2privoxy <socks5_addr:socks5_port>
+# Dependency: base64, curl(https support), perl5 v5.10.0+
+
+# check dependency
+command -v curl &>/dev/null || { echo "curl is not installed in this system" 1>&2; exit 1; }
+command -v perl &>/dev/null || { echo "perl is not installed in this system" 1>&2; exit 1; }
+command -v base64 &>/dev/null || { echo "base64 is not installed in this system" 1>&2; exit 1; }
+
+# temp/output files
+temporary_file=$(mktemp)
 gfwlist_action='gfwlist.action'
 
-## socks5 代理地址，ip:port 格式
-socks5_proxy=$1
-if [[ ! "${socks5_proxy}" =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}:[0-9]{1,5}$ ]]; then
-    echo -e "\e[35minvalid address:\e[0m \"${socks5_proxy}\"" 1>&2
-    echo -e "\e[37mUsage:\e[0m \e[32m$0\e[0m \e[36m'address:port'\e[0m" 1>&2
-    exit 1
-else
-    echo "{+forward-override{forward-socks5 ${socks5_proxy} .}}" > ${gfwlist_action}
-fi
+# parse command line
+test $# -lt 1 && { echo "Usage: sh gfwlist2privoxy <socks5_addr:socks5_port>"; exit 1; }
+perl -e 'exit 1 if $ARGV[0] !~ /^\d+\.\d+\.\d+\.\d+:\d+$/' "$1" || { echo "Invalid address format: '$1'" 1>&2; exit 1; }
+echo -e "# Generated by gfwlist2privoxy at $(date '+%F %T')\n{+forward-override{forward-socks5 $1 .}}" >${gfwlist_action}
 
-## 用到的临时文件
-gfwlist_txt=$(mktemp)
-gfwlist_regex=$(mktemp)
-gfwlist_scheme=$(mktemp)
-gfwlist_begin=$(mktemp)
-gfwlist_main=$(mktemp)
-gfwlist_temp=$(mktemp)
+# convert gfwlist.txt
+curl -4sSkL https://raw.github.com/gfwlist/gfwlist/master/gfwlist.txt | base64 -d | perl -pe '
+s#^\s*+$|^!.*+$|^@@.*+$|^\[AutoProxy.*+$|^/.*/$|^q(?:=|%3d).*+$##gi;
+s@(?:/|%).*+$@@g;
+s@^\|\|?|\|$@@g;
+s@^https?:/?/?@@gi;
+s@(?=[^0-9a-zA-Z.*-]).*+$@@g unless /^\d+\.\d+\.\d+\.\d+(?::\d+)?$/;
+s@^(?!\.|\s*+$|\d+\.\d+\.\d+\.\d+(?::\d+)?$)@.@;
+s@\.?\*$@.@g;
+' | perl -ne 'print unless /^\s*+$/' >${temporary_file}
+echo -e '.google.\n.blogspot.\n.twimg.edgesuite.net' >>${temporary_file}
 
-## 获取 gfwlist.txt
-curl -4sSkL https://raw.github.com/gfwlist/gfwlist/master/gfwlist.txt | base64 -d | grep -Ev '^$|^!|^@@|^\[AutoProxy' > ${gfwlist_txt}
+# conversion completed
+cat ${temporary_file} | perl -ne 'print if /^\d+\.\d+\.\d+\.\d+(?::\d+)?$/' | sort -n | uniq >>${gfwlist_action}
+cat ${temporary_file} | perl -ne 'print unless /^\d+\.\d+\.\d+\.\d+(?::\d+)?$/' | sort | uniq -i >>${gfwlist_action}
+rm -fr ${temporary_file}
+cat << EOF
+Generated file: '${gfwlist_action}'. Please put it in privoxy config directory.
+Usually, the directory is '/etc/privoxy'. If yes, then exec following command:
 
-## 分离不同的语法
-cat ${gfwlist_txt} | grep -E '^/' > ${gfwlist_regex}                # '/regex/' 正则
-cat ${gfwlist_txt} | grep -E '^\|\|' > ${gfwlist_scheme}            # '||pattern' 协议符
-cat ${gfwlist_txt} | grep -E '^\|[^|]' > ${gfwlist_begin}           # '|pattern' 边界符
-cat ${gfwlist_txt} | grep -Ev '^/|^\|\||^\|[^|]' > ${gfwlist_main}  # 语法较为接近的部分
+mv -f ${gfwlist_action} /etc/privoxy
+echo 'actionsfile ${gfwlist_action}' >>/etc/privoxy/config
+service privoxy restart (via SysVinit)
+systemctl restart privoxy.service (via Systemd)
 
-## 处理正则语法 (手动添加)
-echo '.google.' >> ${gfwlist_main}
-echo '.blogspot.' >> ${gfwlist_main}
-echo '.twimg.edgesuite.net' >> ${gfwlist_main}
-
-## 处理协议符，直接删除，privoxy 中没有协议字段
-cat ${gfwlist_scheme} | sed -r 's@^\|\|(.+)$@\1@g' >> ${gfwlist_main}
-
-## 处理边界符，直接删除，然后删除可能有的协议字段
-cat ${gfwlist_begin} | sed -r 's@^\|(.+)$@\1@g; s@^https?:/?/?(.*)$@\1@g' >> ${gfwlist_main}
-
-## 处理 gfwlist_main 文件，去除 uri 等杂项，只要域名
-cat ${gfwlist_main} | sed -r '/^\s*q%3[dD]/ d; s@^([^/%]*).*$@\1@g; s@^[^*]*\*[^.]*\.(.*)$@\1@g; s@^(.*)\.?\*[^.*]*$@\1@g' > ${gfwlist_temp}
-
-## 处理 ipv4 地址
-cat ${gfwlist_temp} | grep -E '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+(:[0-9]+)?$' | sort -n | uniq -i >> ${gfwlist_action}
-
-## 处理域名，添加 .
-cat ${gfwlist_temp} | grep -Ev '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+(:[0-9]+)?$|^\s*$' | sed -r '\@^\.@! s@^(.*)$@.\1@g' | sort | uniq -i >> ${gfwlist_action}
-
-## 处理完毕，删除临时文件
-rm -fr ${gfwlist_txt} ${gfwlist_regex} ${gfwlist_scheme} ${gfwlist_begin} ${gfwlist_main} ${gfwlist_temp}
-
-## 打印接下来要执行的命令（应用 gfwlist_action）
-echo -e "\e[37m# Please execute the following command:\e[0m"
-echo -e "\e[36mcp -af ${gfwlist_action} /etc/privoxy/\e[0m"
-echo -e "\e[36mecho \"actionsfile ${gfwlist_action}\" >> /etc/privoxy/config\e[0m"
-echo -e "\e[37mrestart privoxy service. e.g: 'systemctl restart privoxy.service'\e[0m"
+Enjoy it!
+EOF
